name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - alpha
          - beta
          - stable
      version:
        description: 'Version Number'
        required: true
        type: string
      new_features:
        description: 'New Features'
        required: false
        type: string
      changes:
        description: 'Changes'
        required: false
        type: string
      fixes:
        description: 'Fixes'
        required: false
        type: string
      breaking_changes:
        description: 'Breaking Changes'
        required: false
        type: string
      additional_notes:
        description: 'Additional Notes'
        required: false
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip io_scene_xplane_ext
        run: |
          zip -r Blender-X-Plane-Extensions.zip io_scene_xplane_ext

      - name: Create release notes
        id: notes
        run: |
          if [ "${{ github.event.inputs.release_type }}" = "alpha" ]; then
            foreword="This is an **alpha** release of my unofficial X-Plane Extensions plugin for Blender. Expect instability and incomplete features. Please keep regular backups and do not use in production!"
          elif [ "${{ github.event.inputs.release_type }}" = "beta" ]; then
            foreword="This is a **beta** release of my unofficial X-Plane Extensions plugin for Blender. Features are mostly complete, but bugs may remain."
          else
            foreword="This is a **stable** release of my unofficial X-Plane Extensions plugin for Blender. Recommended for production use."
          fi

          echo "$foreword" > release_notes.md
          echo "" >> release_notes.md
          echo "If you encounter any bugs, please open an issue on the issues tab. If have question/requests, please reach out via any of the contact links in my profile." >> release_notes.md
          echo "" >> release_notes.md
          echo "Please see [wiki](https://github.com/Connor-Russell/Blender-X-Plane-Extensions/wiki) for documentation." >> release_notes.md
          echo "" >> release_notes.md
          echo "# Release Notes" >> release_notes.md

          echo "## New Features" >> release_notes.md
          echo "${{ github.event.inputs.new_features }}" | awk -F';' '{for(i=1;i<=NF;i++) if(length($i)>0) print "- " $i}' >> release_notes.md
          echo "" >> release_notes.md

          echo "## Changes" >> release_notes.md
          echo "${{ github.event.inputs.changes }}" | awk -F';' '{for(i=1;i<=NF;i++) if(length($i)>0) print "- " $i}' >> release_notes.md
          echo "" >> release_notes.md

          echo "## Fixes" >> release_notes.md
          echo "${{ github.event.inputs.fixes }}" | awk -F';' '{for(i=1;i<=NF;i++) if(length($i)>0) print "- " $i}' >> release_notes.md
          echo "" >> release_notes.md

          echo "## Breaking Changes" >> release_notes.md
          echo "${{ github.event.inputs.breaking_changes }}" | awk -F';' '{for(i=1;i<=NF;i++) if(length($i)>0) print "- " $i}' >> release_notes.md
          echo "" >> release_notes.md

          echo "## Additional Notes" >> release_notes.md
          echo "${{ github.event.inputs.additional_notes }}" >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body_path: release_notes.md
          prerelease: ${{ github.event.inputs.release_type != 'stable' }}
          files: Blender-X-Plane-Extensions.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
